### ISSUE TITLE
Run and pass add.js 

### ISSUE THREAD

**Issue by qjivy** [riscv-collab/v8#555]
After pass of [hello.js](https://gist.githubusercontent.com/luyahan/2790ff00df1581b7c458716a7f3563ac/raw/60276bf8ad5262c68bdabddcf0f4317fd1a206ac/gistfile1.txt) , we now move on for add.js:

```
function test(v) {
return v+1;
}
%PrepareFunctionForOptimization(test);
test(1);
%OptimizeFunctionOnNextCall(test);
test(2);
```

**Comment by qjivy** [comment]
First error happens after https://github.com/riscv-collab/v8/pull/554/ merged on debug build：

run cmd:
```
./d8 --allow-natives-syntax  add.js
```

stack backstrace:

```
#0  0xf351f2b5 in v8::base::OS::Abort()::$_0::operator()() const (this=0xff8fced0)
    at ../../src/base/platform/platform-posix.cc:640
#1  0xf351f2a6 in v8::base::OS::Abort () at ../../src/base/platform/platform-posix.cc:640
#2  0xf34e82bb in V8_Fatal (file=0xf44a03dd "../../src/execution/riscv32/simulator-riscv32.cc", line=3098, 
    format=0xf4526282 "Error: Exception %i raised.") at ../../src/base/logging.cc:167
#3  0xf7239880 in v8::internal::Simulator::SignalException (this=0x5793fe00, e=v8::internal::Simulator::kIllegalInstruction)
    at ../../src/execution/riscv32/simulator-riscv32.cc:3098
#4  0xf724e3c7 in v8::internal::Simulator::require (this=0x5793fe00, check=false)
    at ../../src/execution/riscv32/simulator-riscv32.h:647
#5  0xf7243015 in v8::internal::Simulator::DecodeRVIType (this=0x5793fe00)
    at ../../src/execution/riscv32/simulator-riscv32.cc:4546
#6  0xf7235804 in v8::internal::Simulator::InstructionDecode (this=0x5793fe00, instr=0xf559b3cc <Builtins_AddSmiHandler+1100>)
    at ../../src/execution/riscv32/simulator-riscv32.cc:6910
#7  0xf7247a93 in v8::internal::Simulator::Execute (this=0x5793fe00) at ../../src/execution/riscv32/simulator-riscv32.cc:6988
#8  0xf7248085 in v8::internal::Simulator::CallInternal (this=0x5793fe00, entry=4109086336)
    at ../../src/execution/riscv32/simulator-riscv32.cc:7040
#9  0xf724914e in v8::internal::Simulator::CallImpl (this=0x5793fe00, entry=4109086336, argument_count=6, arguments=0xff8fdc40)
    at ../../src/execution/riscv32/simulator-riscv32.cc:7117
```

potential cause: generate of srli instructions

lines from simulator-riscv32.cc: 
```
4541     case RO_SRLI: {  //  RO_SRAI                            
4542       if (!instr_.IsArithShift()) { 
4543         require(shamt6() < xlen);                           
4544         set_rd(sext_xlen(zext_xlen(rs1()) >> shamt6()));    
4545       } else {
4546         require(shamt6() < xlen);
4547         set_rd(sext_xlen(sext_xlen(rs1()) >> shamt6()));    
4548       }                                                     
4549       break;                                                
4550     }
```

**Comment by qjivy** [comment]
Done after https://github.com/riscv-collab/v8/pull/568
